
###
GET https://aquaponic.onrender.com/api/get_data?result=0&start=0
Accept: application/json, text/plain, */*


###
POST http://localhost:5000/api/send
Content-Type: application/json

{"temperature":"55","led_status":"true","ph_leveling":"42","tds":"151.25","value2":"49.54","value3":"1005.14"}